steps:
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=gke-resource.yaml
    - --location=us-east1
    - --cluster=my-auto-cluster-east
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=gke-resource.yaml
    - --location=us-central1
    - --cluster=my-auto-cluster-central
